name: Vanubuntu Daily Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build ISOs
        run: sudo bash ./vanubuntu.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Vanubuntu Linux daily build ISO
          path: |
            /root/ubuntu-vanilla-gnome-*.iso
